# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smoothdb < Formula
  desc ""
  homepage ""
  version "0.2.8"

  on_macos do
    on_intel do
      url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Darwin_x86_64.tar.gz"
      sha256 "ce4efef6a726a4fe591cfc19949fcd71a3dfb8c06ad31874551401573ae84b1e"

      def install
        bin.install "smoothdb"
      end
    end
    on_arm do
      url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Darwin_arm64.tar.gz"
      sha256 "a1183b239f709b58bdd0fb8b24ac0f1ea7a0b272af9ef2e05c757fafb2321895"

      def install
        bin.install "smoothdb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Linux_x86_64.tar.gz"
        sha256 "c89767237f7917fae5eb65efeec9d582642dede237eddb069489d0b2736806cc"

        def install
          bin.install "smoothdb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Linux_arm64.tar.gz"
        sha256 "409e78a21d5a85af7bcf951b020327f7875374596d906ffa5916347302f98ced"

        def install
          bin.install "smoothdb"
        end
      end
    end
  end
end
