# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smoothdb < Formula
  desc ""
  homepage ""
  version "0.2.8"

  on_macos do
    on_intel do
      url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Darwin_x86_64.tar.gz"
      sha256 "5118979df7bf8cbccc5e63d5befe8f94576add83ab9f0e2626ddf7bc3e17bd16"

      def install
        bin.install "smoothdb"
      end
    end
    on_arm do
      url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Darwin_arm64.tar.gz"
      sha256 "9e1e70adc938e66f55abe25f8301aea5a2b2661d95f98377bd0f48b15877f9cf"

      def install
        bin.install "smoothdb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Linux_x86_64.tar.gz"
        sha256 "701979f0cbc4e4dc4d928d72d7f04457b3a4b7dad5150c7ad05a307a1fcbb718"

        def install
          bin.install "smoothdb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sted/smoothdb/releases/download/v0.2.8/smoothdb_Linux_arm64.tar.gz"
        sha256 "07dc2130037ecedd22b08735dda162273340357ed389cab76ece0d051357b5a2"

        def install
          bin.install "smoothdb"
        end
      end
    end
  end
end
