# This file was generated by GoReleaser. DO NOT EDIT.
cask "smoothdb" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "ef9b471f122a8306459719654e3d68f9872cc7a5d36e8b29873936db306b472c"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "059e8e21122cf808064750c5692095e675d91341f7447e4f6dc8ff2032492684"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1c7a93a25e6581d8f9ee78313727de6a749d4bd1e8d60d4a744ba23108dd6d21"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d0d3e696a1d92c470a22cdf7ba1680afe17b9dccee5ffd7364972cf37ffaee0"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Linux_x86_64.tar.gz"
    end
  end

  name "smoothdb"
  desc "RESTful API for PostgreSQL databases"
  homepage "https://github.com/sted/smoothdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smoothdb"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smoothdb"] if OS.mac?
  end

  # No zap stanza required
end
