# This file was generated by GoReleaser. DO NOT EDIT.
cask "smoothdb" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "61d8074c1839d57ff0840de18266668595e6eebb33c5ddcfe7a3ae8044f0ce1a"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc217dc423487a77bf235007f5fdf2745f3040ad1b4c09c38315e9bb7d8da943"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b9f52483ba0e5f57f131eb7085253d0a72d4733aede7c3523b6b544e5570c705"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0ab90310a5d51957eae9c2bca0a6640a5e20206994acbd65aafdce41a3cee24"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Linux_x86_64.tar.gz"
    end
  end

  name "smoothdb"
  desc "RESTful API for PostgreSQL databases"
  homepage "https://github.com/sted/smoothdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smoothdb"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smoothdb"] if OS.mac?
  end

  # No zap stanza required
end
