# This file was generated by GoReleaser. DO NOT EDIT.
cask "smoothdb" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "6ed07f55179b7ab4efe50a6ca7f23401c175b92c8fb7332cbc9842a86c8f6158"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c173c61a5dfeefb9750bb0961c7816d6467e687fe391e21deb1197cec3f6b559"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e4192aacf5dcfcace5fc8d2484f86712426e50217943f98e9a112f140521f557"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e64270ab4f328fe9d374b7b7be225313711f7364d4030882eb8ee5c196d2094e"
      url "https://github.com/sted/smoothdb/releases/download/v#{version}/smoothdb_Linux_x86_64.tar.gz"
    end
  end

  name "smoothdb"
  desc "RESTful API for PostgreSQL databases"
  homepage "https://github.com/sted/smoothdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smoothdb"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smoothdb"] if OS.mac?
  end

  # No zap stanza required
end
