# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smoothdb < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sted/smoothdb/releases/download/v0.3.0/smoothdb_Darwin_x86_64.tar.gz"
      sha256 "3374438b2014512b50b70d2cc3cae7e7e78df0c3e09731387a80cde36b1b033c"

      def install
        bin.install "smoothdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sted/smoothdb/releases/download/v0.3.0/smoothdb_Darwin_arm64.tar.gz"
      sha256 "01c27b8d539f868ee6a0bede455f9b15684158b910ffe52d68c51d52b2d00e6f"

      def install
        bin.install "smoothdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sted/smoothdb/releases/download/v0.3.0/smoothdb_Linux_x86_64.tar.gz"
      sha256 "a591a69ff492014263faecf03c35c54fa780f031d0edae50dd9527e38306aa04"
      def install
        bin.install "smoothdb"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sted/smoothdb/releases/download/v0.3.0/smoothdb_Linux_arm64.tar.gz"
      sha256 "637ce900680986b78dc2ec3a1be3db22316d577819c1a3af7f673bd84bf642a8"
      def install
        bin.install "smoothdb"
      end
    end
  end
end
